name: Metrics

permissions:
  contents: write

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          # TOKEN
          token: ${{ secrets.METRICS_TOKEN }}

    
          user: NicooJs

          # CONFIGURAÇÕES DE COMMIT 
          committer_branch: main
          committer_message: "chore: update github metrics"
          committer_username: NicoJs
          committer_email: nicolasarantescamargo@gmail.com

          # TEMPLATE
          template: classic

          # BASE
          base: header, activity, repositories

          # TIMEZONE
          config_timezone: America/Sao_Paulo

          # PLUGINS
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 6

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_followup: yes

          # ARQUIVO GERADO
          filename: github-metrics.svg
